config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'
  get 'projects/new', to: 'projects#new'
  post 'projects', to: 'projects#create'

  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  enum state:[:propuesta, :en_progreso, :terminado]
  validates :name, presence: true
  validates :description, presence: true
  validates :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    if @project.save
      redirect_to root_path, notice: 'Se ha creado el proyecto'
    else
      redirect_to root_path, alert: 'No se guardo el proyecto'
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :state, :initial_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorProyectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb
<div class="container">
  <form> 
      <p>Buscar proyecto por estado:</p>
      <div class="col-md-3 mb-3">
        <label for="validationDefault04">Estado del proyecto</label>
        <select class="custom-select" name="state">
          <option value= "0" >propuesta</option>
          <option value= "1" >En Progreso</option>
          <option value= "2 ">Termiando</option>
          <option value= "">todo</option>
        </select>
      </div>
    <button class="btn btn-success" type="submit">Buscar proyecto</button>
  </form>
</div>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Descripcion</th>
        <th scope="col">Estado</th>
        <th scope="col">Fecha de Inicio</th>
        <th scope="col">Fecha de Termino</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project|%>
      <tr>
        <td> <%= project.id%> </td>
        <td> <%= project.name%> </td>
        <td> <%= project.description%> </td>
        <td> <%= project.state%> </td>
        <td> <%= project.initial_date%> </td>
        <td> <%= project.end_date%> </td>
      </tr>
      <% end%>
    </tbody>
  </table>

  <%= link_to 'Nuevo Proyecto', projects_new_path, class: 'btn btn-success'%>

</div>

app/views/projects/new.html.erb
<%= form_with(model: @project, local: true) do |f|%>
  <div class='form-group'>
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>
  <div class='form-group'>
    <%= f.label :description%>
    <%= f.text_field :description%>
  </div>
  <div class='form-group'>
    <%= f.label :state%>
    <%= f.select :state, options_for_select(Project.states.keys)%>
  </div>
  <div class='form-group'>
    <%= f.label :initial_date%>
    <%= f.date_field :initial_date%>
  </div>
  <div class='form-group'>
    <%= f.label :end_date%>
    <%= f.date_field :end_date%>
  </div>
  <%= f.submit 'Crear Proyecto', class: 'btn btn-success'%>
<% end %>